"""
src/utils/lineage.py

Manages reading, compiling, and tracking the data lineage metadata for the pipeline.
Fully compatible with the JSON schemas generated by bronze_ingest.py.

The lineage metadata is a structured JSON tracking file accumulating data slices across stages:
- Bronze: Generated independently by bronze_ingest.py (pre-existing target)
- Silver: This tracking interface injects the 'silver' validation layer metadata block
- Gold:   This tracking interface injects the 'gold' metric summarization metadata block

Design Principles:
- Pure serialization functions — entirely free of side-effects outside explicit file system I/O
- Idempotent: Overwriting a specific pipeline stage section does not alter or corrupt adjacent layers
- Strict Python 3.8 compatibility compliance (explicit Optional[X] over PEP 604 union types)

Default System Path Locations:
    data/lineage/bronze_metadata.json  ← Generated during bronze_ingest.py execution
    data/lineage/silver_metadata.json  ← Generated during silver_transform.py execution
    data/lineage/pipeline_lineage.json ← Complete consolidated tracking map for the pipeline
"""

import json
import logging
import os
from datetime import datetime, timezone
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)

# Default Storage Paths
BRONZE_LINEAGE_PATH   = "data/lineage/bronze_metadata.json"
SILVER_LINEAGE_PATH   = "data/lineage/silver_metadata.json"
PIPELINE_LINEAGE_PATH = "data/lineage/pipeline_lineage.json"


# ─────────────────────────────────────────────
#  Read Operations
# ─────────────────────────────────────────────

def load_lineage(path: str) -> Dict[str, Any]:
    """
    Reads and extracts a pipeline lineage JSON file from disk storage.

    Args:
        path: Target file system destination route for the JSON metadata tracker

    Returns:
        Dict mapping containing the serialized metadata layer blocks.
        Returns an empty dictionary fallback if the file does not exist (initial execution safe path).
    """
    if not os.path.exists(path):
        logger.warning("Lineage tracking file target not found at %s — initializing fallback empty tracking layer", path)
        return {}

    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    logger.info("Lineage metadata state successfully recovered from storage path: %s", path)
    return data


def load_bronze_lineage(path: str = BRONZE_LINEAGE_PATH) -> Dict[str, Any]:
    """
    Extracts the foundational Bronze-tier lineage generated directly by bronze_ingest.py.
    Provides an explicit semantic operational wrapper over load_lineage for tracking clarity.
    """
    data = load_lineage(path)
    if not data:
        logger.warning(
            "Bronze lineage tracking context resolved to empty — verify if bronze_ingest.py was executed first."
        )
    return data


# ─────────────────────────────────────────────
#  Write Operations
# ─────────────────────────────────────────────

def save_lineage(data: Dict[str, Any], path: str) -> None:
    """
    Serializes an operational lineage map block directly to a structured, pretty-printed JSON file.
    Automatically handles any missing directory tracks required by the storage target path.

    Args:
        data: Metadata map structure targeting serialization.
        path: Physical file target system location track.
    """
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    logger.info("Lineage tracking updates completely flushed to disk storage path: %s", path)


# ─────────────────────────────────────────────
#  Metadata Layer Builders
# ─────────────────────────────────────────────

def build_silver_lineage(
    bronze_lineage:       Dict[str, Any],
    silver_row_count:      int,
    quarantine_row_count: int,
    tissue_count:          int,
    chunk_plan_summary:   str,
    quality_report_dict:  Dict[str, Any],
    infra_fingerprint:    str,
    memory_used:          str,
    duration_seconds:     Optional[float] = None,
) -> Dict[str, Any]:
    """
    Constructs the operational lineage tracking record for the Silver processing tier.
    Links the tracking profile upstream back to the parent Bronze source block for full data traceability.

    Args:
        bronze_lineage:       Upstream mapping tracking state loaded via load_bronze_lineage()
        silver_row_count:      Active data row counts committed to the Silver Delta location
        quarantine_row_count: Discarded row records directed out to quarantine locations
        tissue_count:          Distinct, unique tissue dimensions extracted into Silver structures
        chunk_plan_summary:   Extracted performance profile string from ChunkPlan.summary()
        quality_report_dict:  Serialized quality data mappings from QualityReport.to_dict()
        infra_fingerprint:    Unique SHA-256 target string identifying the target execution infrastructure
        memory_used:          Physical RAM resource metrics utilized during run loops (e.g., '3g')
        duration_seconds:     Unified execution processing timeframe metric track for the job

    Returns:
        Structured dictionary target completely aligned for save_lineage validation schemas.
    """
    bronze_genes   = 74_628
    bronze_samples = 19_788
    expected_total = bronze_genes * bronze_samples
    actual_total   = silver_row_count + quarantine_row_count
    lineage_closes = actual_total == expected_total

    return {
        "layer":                "silver",
        "generated_at_utc":     datetime.now(timezone.utc).isoformat(),
        "infra_fingerprint":    infra_fingerprint,
        "memory_used":          memory_used,

        # Traceability pointers mapping back upstream to the Bronze execution tier
        "source": {
            "layer":              "bronze",
            "path":               bronze_lineage.get("bronze_path", "unknown"),
            "size_bytes":         bronze_lineage.get("bronze_size_bytes", 0),
            "ingestion_ts":       bronze_lineage.get("ingestion_timestamp", "unknown"),
            "bronze_fingerprint": bronze_lineage.get("infra_fingerprint", "unknown"),
        },

        # Silver Core Execution Outputs
        "output": {
            "path":              "data/silver/gtex/gene_expression_long/",
            "format":            "delta",
            "compression":       "snappy",
            "partition_col":     "tissue_id",
            "tissue_count":      tissue_count,
            "row_count":         silver_row_count,
            "quarantine_count":  quarantine_row_count,
            "quarantine_path":   "data/quarantine/silver_unmatched_samples.parquet",
        },

        # Pipeline Mathematical Audit Verification Gate (Data Closure Check)
        "lineage_closure": {
            "bronze_genes":    bronze_genes,
            "bronze_samples":  bronze_samples,
            "expected_total":  expected_total,
            "actual_total":    actual_total,
            "closes":          lineage_closes,
            "delta":           actual_total - expected_total,
        },

        # Documented Transformations Applied in Processing Stream
        "transformations": [
            "wide→long reshape (pandas chunks, 200 cols/chunk)",
            "join sample_id → tissue_id (gtex_metadata.txt)",
            "cast gene_id=string, gene_symbol=string, sample_id=string, tpm_value=float",
            "zeros preserved (biologically valid expressions)",
            "unmatched samples → quarantine destination tracks",
        ],

        # Performance Architecture Audit
        "performance": {
            "chunk_plan":        chunk_plan_summary,
            "duration_seconds": duration_seconds,
        },

        # Quality Gate Metrics Mapping
        "quality_report": quality_report_dict,
    }


def build_gold_lineage(
    silver_lineage:      Dict[str, Any],
    gold_row_count:      int,
    tissue_count:        int,
    quality_report_dict: Dict[str, Any],
    infra_fingerprint:    str,
    memory_used:          str,
    duration_seconds:     Optional[float] = None,
) -> Dict[str, Any]:
    """
    Constructs the operational lineage tracking record for the Gold processing tier.
    Maintains a strict traceability chain pointing back to the derived upstream Silver block tracking record.
    """
    return {
        "layer":             "gold",
        "generated_at_utc":  datetime.now(timezone.utc).isoformat(),
        "infra_fingerprint": infra_fingerprint,
        "memory_used":       memory_used,

        "source": {
            "layer":       "silver",
            "path":        silver_lineage.get("output", {}).get("path", "unknown"),
            "row_count":   silver_lineage.get("output", {}).get("row_count", 0),
            "silver_ts":   silver_lineage.get("generated_at_utc", "unknown"),
        },

        "output": {
            "path":          "data/gold/gtex/gene_tissue_summary/",
            "format":        "delta",
            "compression":   "zstd",
            "partition_col": "tissue_id",
            "tissue_count":  tissue_count,
            "row_count":     gold_row_count,
        },

        "transformations": [
            "groupBy(gene_id, gene_symbol, tissue_id)",
            "agg: mean/median/std compute passes over log1p(tpm_value)",
            "agg: count(sample_id) → sample_count mappings",
            "agg: zero_fraction = sum(tpm==0) / total count tracks",
            "log1p transformation evaluated inside Gold aggregates (structural zeros completely skipped during mean profiling logic)",
        ],

        "performance": {
            "duration_seconds": duration_seconds,
        },

        "quality_report": quality_report_dict,
    }


# ─────────────────────────────────────────────
#  Unified Consolidated Pipeline Tracking
# ─────────────────────────────────────────────

def build_pipeline_lineage(
    bronze_lineage: Dict[str, Any],
    silver_lineage: Optional[Dict[str, Any]] = None,
    gold_lineage:   Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """
    Aggregates metrics across individual pipeline tiers to output an end-to-end lineage visualization artifact.
    Serves as an operational source map utilized to automatically populate pipeline README structures or operational logs.

    Args:
        bronze_lineage: Metadata trace map from the Bronze ingestion engine (strictly required)
        silver_lineage: Metadata trace map from the Silver transform engine (None if processing block is skipped/pending)
        gold_lineage:   Metadata trace map from the Gold aggregation engine (None if processing block is skipped/pending)

    Returns:
        Unified dictionary map tracking layers status, data volumes, and state records.
    """
    layers_complete = sum([
        1,                              # Bronze verification tracking layer guarantees baseline presence
        1 if silver_lineage else 0,
        1 if gold_lineage else 0,
    ])

    return {
        "pipeline":         "bio-ai-lakehouse",
        "dataset":          "GTEx Gene Expression v11",
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "layers_complete":  f"{layers_complete}/3",
        "status":           "complete" if layers_complete == 3 else "in_progress",
        "bronze":           bronze_lineage,
        "silver":           silver_lineage or {"status": "pending"},
        "gold":             gold_lineage   or {"status": "pending"},
    }


# ─────────────────────────────────────────────
#  Local Integration Validation Harness Sandbox (CLI Targets)
# ─────────────────────────────────────────────

if __name__ == "__main__":
    print("\n── Executing Lineage Verification Smoke Test Sandbox ─────────────────\n")

    # 1. Attempt Retrieval of Pre-Existing Bronze Metadata Traces
    bronze = load_bronze_lineage()
    if bronze:
        print(f"✅ Baseline Bronze lineage metadata structures successfully loaded from local tracking files.")
        print(f"    Source Target Entry File: {bronze.get('source_file', 'N/A')}")
        print(f"    Source Capacity footprint (GB): {bronze.get('source_size_gb', 'N/A')}")
        print(f"    Data Ingestion Timestamp: {bronze.get('ingestion_timestamp', 'N/A')}")
    else:
        print("⚠️ Upstream Bronze metadata tracking files absent from environment profiles — establishing mock profile traces.")
        bronze = {
            "source_file":       "data/raw/GTEx_Analysis_...parquet",
            "source_size_gb":    4.02,
            "bronze_path":       "data/bronze/gtex/gene_tpm_raw.parquet",
            "bronze_size_bytes": 4314964228,
            "ingestion_timestamp": "2026-04-30T03:31:16.043239+00:00",
            "infra_fingerprint": "fceb44ab17161175",
            "memory_used":       "4g",
            "override_applied":  True,
        }

    # 2. Simulate Execution Outputs and Profile Silver Lineage Structure Behavior
    silver = build_silver_lineage(
        bronze_lineage       = bronze,
        silver_row_count     = 74_628 * 19_788,
        quarantine_row_count = 0,
        tissue_count         = 54,
        chunk_plan_summary   = "partitions=20, allocation_RAM=3g, execution_cores=5, ~14.0 min computed timeframe",
        quality_report_dict  = {"layer": "silver", "passed": True, "checks": []},
        infra_fingerprint    = "fceb44ab17161175",
        memory_used          = "3g",
        duration_seconds     = 840.0,
    )
    print(f"\n✅ Target Silver validation tracking profiles successfully compiled.")
    print(f"    Dispatched Output Rows Volume: {silver['output']['row_count']:,}")
    print(f"    Data Integrity Mathematical Closure Gate Status: {silver['lineage_closure']['closes']}")
    print(f"    Calculated Variance Discrepancy Level (Delta): {silver['lineage_closure']['delta']}")

    # 3. Compile Unified Lakehouse Lineage Map (Simulating Pending Gold Evaluation State)
    pipeline = build_pipeline_lineage(bronze, silver)
    print(f"\n✅ Consolidated end-to-end architecture tracking profile unified: {pipeline['layers_complete']} processing layers compiled completely.")
    print(f"    Global Operational Processing Status State: {pipeline['status']}")

    # 4. Flush Changes and Test File System I/O Persistence Layers
    save_lineage(silver,   SILVER_LINEAGE_PATH)
    save_lineage(pipeline, PIPELINE_LINEAGE_PATH)
    print(f"\n✅ Validation lineage structural output artifacts successfully committed to storage tracks:")
    print(f"    -> {SILVER_LINEAGE_PATH}")
    print(f"    -> {PIPELINE_LINEAGE_PATH}")
